# Generated by Django 5.2.15 on 2026-09-13 05:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cache_key", models.CharField(max_length=64, unique=True)),
                ("question", models.TextField()),
                ("collection", models.CharField(blank=True, max_length=160)),
                ("target", models.TextField()),
                ("model", models.CharField(max_length=255)),
                ("scope_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="queued", max_length=16)),
                ("units", models.JSONField(default=list)),
                ("next_unit", models.PositiveIntegerField(default=0)),
                ("document_count", models.PositiveIntegerField(default=0)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("missing_documents", models.JSONField(default=list)),
                ("entries", models.JSONField(default=dict)),
                ("request_metadata", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "query",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chat.chatquery",
                    ),
                ),
            ],
        ),
    ]
