# Generated by Django 5.2.15 on 2026-09-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_collectionanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionanalysis",
            name="unverified_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
