# Generated by Django 5.2.15 on 2026-09-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_collectionanalysis_unverified_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionanalysis",
            name="skipped_units",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
