# Generated by Django 5.2.15 on 2026-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_collectionanalysis_skipped_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedArtifact",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("kind", models.CharField(db_index=True, max_length=16)),
                ("value", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="collectionanalysis",
            name="cached_units",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
