# Generated by Django 5.2.15 on 2026-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_cachedartifact_collectionanalysis_cached_units"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="collectionanalysis",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "running")),
                fields=("status",),
                name="one_collection_review_running",
            ),
        ),
    ]
