# Generated by Django 5.2.15 on 2026-09-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_collectionanalysis_one_collection_review_running"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionanalysis",
            name="excluded",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="collectionanalysis",
            name="kind",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="collectionanalysis",
            name="restriction",
            field=models.TextField(blank=True),
        ),
    ]
