# Generated by Django 5.2.15 on 2026-09-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_collectionanalysis_excluded_collectionanalysis_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionanalysis",
            name="filter_failures",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
