# Generated by Django 5.2.15 on 2026-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0005_unrecorded_run_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationrun",
            name="chunk_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="corpus_chunk_count",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
