"use client";

import {
  AlertCircle,
  FileSearch,
  MessageSquareText,
  Send,
  SlidersHorizontal,
} from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import { CitationCard } from "@/components/citation-card";
import { EmptyState } from "@/components/empty-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { SafeIcon } from "@/components/ui/safe-icon";
import { Skeleton } from "@/components/ui/skeleton";
import { api, getErrorMessage } from "@/lib/api";
import { formatLatency, formatScore, lineRange } from "@/lib/format";
import type { ChatResponse, Collection, RetrievalMode } from "@/types/api";

type ConversationItem = {
  question: string;
  response: ChatResponse;
};

function answerModeLabel(mode: ChatResponse["metadata"]["answer_mode"]) {
  if (mode === "generated") return "local LLM";
  if (mode === "extractive") return "extractive fallback";
  return "no results";
}

function answerModeDescription(response: ChatResponse) {
  if (response.metadata.answer_mode === "generated") {
    return "The answer was generated by the configured local answer model using retrieved source context.";
  }
  if (response.metadata.answer_mode === "extractive") {
    return "The local answer model was unavailable, so the backend returned an extractive answer from retrieved chunks.";
  }
  return "The retriever did not return matching chunks for this question.";
}

export function ChatClient() {
  const [collections, setCollections] = useState<Collection[]>([]);
  const [question, setQuestion] = useState("");
  const [collection, setCollection] = useState("");
  const [retrievalMode, setRetrievalMode] = useState<RetrievalMode>("hybrid");
  const [topK, setTopK] = useState(5);
  const [rerank, setRerank] = useState(true);
  const [conversation, setConversation] = useState<ConversationItem[]>([]);
  const [loadingCollections, setLoadingCollections] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    api
      .collections()
      .then((data) => {
        if (active) {
          setCollections(data);
        }
      })
      .catch((err) => {
        if (active) {
          setError(getErrorMessage(err));
        }
      })
      .finally(() => {
        if (active) {
          setLoadingCollections(false);
        }
      });
    return () => {
      active = false;
    };
  }, []);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!question.trim()) {
      setError("Enter a question before sending.");
      return;
    }

    try {
      setSubmitting(true);
      setError(null);
      const response = await api.chatQuery({
        question,
        collection: collection || undefined,
        retrieval_mode: retrievalMode,
        top_k: topK,
        rerank,
      });
      setConversation((current) => [{ question, response }, ...current]);
      setQuestion("");
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setSubmitting(false);
    }
  }

  const latest = conversation[0]?.response;

  return (
    <>
      <section className="flex flex-col gap-2">
        <h1 className="text-3xl font-semibold">RAG chat</h1>
        <p className="text-muted-foreground">
          Ask local documents and inspect every cited source chunk, retrieval
          score, and page or line range behind the answer.
        </p>
      </section>

      <div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(320px,390px)]">
        <Card className="min-h-[660px] min-w-0">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <SafeIcon icon={MessageSquareText} />
              Conversation
            </CardTitle>
            <CardDescription>
              Answers cite retrieved chunks as [n]. Empty retrieval and local
              model fallback states are shown explicitly.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex min-h-[540px] flex-col justify-between gap-6">
            <div className="flex flex-col gap-5">
              {conversation.length ? (
                conversation.map((item, index) => (
                  <article
                    key={`${item.question}-${index}`}
                    className="grid gap-3 rounded-md border bg-background p-4"
                  >
                    <div className="flex flex-col gap-2 rounded-md bg-muted/60 p-3">
                      <span className="text-xs font-medium text-muted-foreground">
                        Question
                      </span>
                      <p className="text-sm leading-6">{item.question}</p>
                    </div>
                    <div className="grid gap-3">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge variant="secondary">
                          {answerModeLabel(item.response.metadata.answer_mode)}
                        </Badge>
                        <Badge variant="outline">
                          {item.response.citations.length} citations
                        </Badge>
                        <Badge variant="outline">
                          {item.response.metadata.retrieval_mode}
                        </Badge>
                        <Badge variant="outline">
                          {formatLatency(item.response.metadata.latency_ms)}
                        </Badge>
                      </div>
                      <p className="text-xs leading-5 text-muted-foreground">
                        {answerModeDescription(item.response)}
                      </p>
                      {item.response.metadata.generation_error ? (
                        <p className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive">
                          Local model fallback:{" "}
                          {item.response.metadata.generation_error}
                        </p>
                      ) : null}
                      <p className="whitespace-pre-line text-sm leading-7">
                        {item.response.answer}
                      </p>
                    </div>
                  </article>
                ))
              ) : (
                <EmptyState
                  icon={FileSearch}
                  title="Ask your indexed documents"
                  description="Try receipt questions like visible dates, totals, vendors, IDs, or which source file supports the answer."
                />
              )}
              {submitting ? <Skeleton className="h-32 w-full" /> : null}
              {error ? (
                <div className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
                  <SafeIcon icon={AlertCircle} />
                  <span className="ml-2">{error}</span>
                </div>
              ) : null}
            </div>

            <form
              className="rounded-md border bg-background p-3"
              onSubmit={handleSubmit}
            >
              <div className="mb-3 grid gap-3 md:grid-cols-4">
                <select
                  className="h-10 rounded-md border bg-background px-3 text-sm"
                  value={collection}
                  onChange={(event) => setCollection(event.target.value)}
                  aria-label="Collection"
                  disabled={loadingCollections}
                >
                  <option value="">All collections</option>
                  {collections.map((item) => (
                    <option key={item.id} value={item.name}>
                      {item.name}
                    </option>
                  ))}
                </select>
                <select
                  className="h-10 rounded-md border bg-background px-3 text-sm"
                  value={retrievalMode}
                  onChange={(event) =>
                    setRetrievalMode(event.target.value as RetrievalMode)
                  }
                  aria-label="Retrieval mode"
                >
                  <option value="hybrid">hybrid</option>
                  <option value="vector">vector</option>
                  <option value="metadata-filtered">metadata-filtered</option>
                </select>
                <Input
                  type="number"
                  min={1}
                  max={20}
                  value={topK}
                  onChange={(event) => setTopK(Number(event.target.value))}
                  aria-label="Top k"
                />
                <label className="flex h-10 items-center gap-2 rounded-md border px-3 text-sm">
                  <input
                    type="checkbox"
                    checked={rerank}
                    onChange={(event) => setRerank(event.target.checked)}
                  />
                  Rerank
                </label>
              </div>
              <div className="flex gap-3">
                <Input
                  value={question}
                  onChange={(event) => setQuestion(event.target.value)}
                  placeholder="What dates, totals, vendors, or source files are visible?"
                />
                <Button disabled={submitting}>
                  <SafeIcon icon={Send} />
                  {submitting ? "Sending" : "Send"}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>

        <div className="flex min-w-0 flex-col gap-4">
          <Card className="min-w-0">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <SafeIcon icon={SlidersHorizontal} />
                Retrieval settings
              </CardTitle>
              <CardDescription>
                Latest response metadata returned by the chat endpoint.
              </CardDescription>
            </CardHeader>
            <CardContent className="grid gap-3 text-sm">
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Embedding</span>
                <span className="min-w-0 truncate text-right font-medium">
                  {latest?.metadata.embedding_model ?? "Pending"}
                </span>
              </div>
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Answer model</span>
                <span className="min-w-0 truncate text-right font-medium">
                  {latest?.metadata.llm_model ?? "Pending"}
                </span>
              </div>
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Top-k</span>
                <span className="text-right font-medium">
                  {latest?.metadata.retrieval_top_k ?? topK}
                </span>
              </div>
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Rerank</span>
                <span className="text-right font-medium">
                  {String(latest?.metadata.rerank ?? rerank)}
                </span>
              </div>
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Retrieval latency</span>
                <span className="text-right font-medium">
                  {latest
                    ? formatLatency(latest.metadata.retrieval_latency_ms)
                    : "Pending"}
                </span>
              </div>
            </CardContent>
          </Card>

          {latest?.citations.length ? (
            latest.citations.map((citation) => (
              <CitationCard
                key={citation.chunk_id}
                sourceNumber={citation.source_number}
                document={citation.document}
                documentId={citation.document_id}
                chunkId={citation.chunk_id}
                retrievalSource={citation.retrieval_source}
                range={lineRange(
                  citation.start_line,
                  citation.end_line,
                  citation.page,
                )}
                score={formatScore(citation.score)}
                text={citation.text_preview}
              />
            ))
          ) : (
            <Card>
              <CardHeader>
                <CardTitle>Retrieved evidence</CardTitle>
                <CardDescription>
                  {latest
                    ? "The latest answer did not include citations."
                    : "Cited source chunks will appear here after a question."}
                </CardDescription>
              </CardHeader>
            </Card>
          )}
        </div>
      </div>
    </>
  );
}
