"use client";

import {
  AlertCircle,
  FileSearch,
  MessageSquareText,
  Send,
  SlidersHorizontal,
} from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import { ResultSources } from "@/components/chat/result-sources";
import { ReviewProgress } from "@/components/chat/review-progress";
import { CitationCard } from "@/components/citation-card";
import { EmptyState } from "@/components/empty-state";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { SafeIcon } from "@/components/ui/safe-icon";
import { Skeleton } from "@/components/ui/skeleton";
import { api, getErrorMessage } from "@/lib/api";
import {
  downloadInventory,
  INVENTORY_PREVIEW_LIMIT,
} from "@/lib/inventory-export";
import { formatLatency, formatScore, lineRange } from "@/lib/format";
import type { ChatResponse, Collection, RetrievalMode } from "@/types/api";

type ConversationItem = {
  question: string;
  response: ChatResponse;
};

function answerModeLabel(mode: ChatResponse["metadata"]["answer_mode"]) {
  if (mode === "review_references") return "saved sources";
  if (mode === "collection_analysis") return "full collection review";
  if (mode === "generated") return "local LLM";
  if (mode === "extractive") return "extractive fallback";
  return "no results";
}

function citationStatusLabel(response: ChatResponse) {
  const status = response.metadata.citation_status;
  if (status === "valid") return "citations reference supplied sources";
  if (status === "missing") return "answer has no citation markers";
  if (status === "invalid_references") return "invalid citations rejected";
  return null;
}

function answerModeDescription(response: ChatResponse) {
  if (response.metadata.answer_mode === "review_references")
    return "Source evidence loaded from a saved review, without another model call.";
  if (response.metadata.answer_cached) {
    return "Reused a saved local-model answer for the same question and unchanged retrieved evidence.";
  }
  if (response.metadata.answer_mode === "generated") {
    return "The answer was generated by the configured local answer model using retrieved source context.";
  }
  if (response.metadata.answer_mode === "extractive") {
    return "The local answer model was unavailable, so the backend returned an extractive answer from retrieved chunks.";
  }
  return "The retriever did not return matching chunks for this question.";
}

function retrievalCoverageDescription(response: ChatResponse) {
  const sources =
    response.metadata.retrieved_source_count ?? response.citations.length;
  const documents = response.metadata.collection_document_count;
  const chunks = response.metadata.collection_chunk_count;
  const size =
    documents != null && chunks != null
      ? `Search scope: ${documents} documents, ${chunks} stored chunks.`
      : "Search scope size unavailable.";
  return `Retrieved source chunks: ${sources}. ${size} Retrieved passages are a partial sample, not a complete collection review.`;
}

export function ChatClient() {
  const [collections, setCollections] = useState<Collection[]>([]);
  const [question, setQuestion] = useState("");
  const [collection, setCollection] = useState("");
  const [retrievalMode, setRetrievalMode] = useState<RetrievalMode>("hybrid");
  const [topK, setTopK] = useState(5);
  const [analysisScope, setAnalysisScope] = useState<
    "auto" | "retrieved" | "collection"
  >("auto");
  const [rerank, setRerank] = useState(true);
  const [conversation, setConversation] = useState<ConversationItem[]>([]);
  const [loadingCollections, setLoadingCollections] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [controllingReview, setControllingReview] = useState<string | null>(
    null,
  );
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    api
      .collections()
      .then((data) => {
        if (active) {
          setCollections(data);
        }
      })
      .catch((err) => {
        if (active) {
          setError(getErrorMessage(err));
        }
      })
      .finally(() => {
        if (active) {
          setLoadingCollections(false);
        }
      });
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    let active = true;
    api
      .chatActiveAnalyses()
      .then((responses) => {
        if (active)
          setConversation((items) => [
            ...responses
              .filter(
                (response) =>
                  !items.some(
                    (item) =>
                      item.response.metadata.analysis_id ===
                      response.metadata.analysis_id,
                  ),
              )
              .map((response) => ({
                question: response.question ?? "Collection review",
                response,
              })),
            ...items,
          ]);
      })
      .catch((err) => {
        if (active) setError(getErrorMessage(err));
      });
    return () => {
      active = false;
    };
  }, []);

  async function controlReview(id: string, action: "cancel" | "resume") {
    try {
      setControllingReview(id);
      const response = await api.chatAnalysisControl(id, action);
      setConversation((items) =>
        items.map((item) =>
          // Only the review item itself. A saved-reference reply shares the
          // review id and must not be replaced by the review response.
          item.response.metadata.answer_mode === "collection_analysis" &&
          item.response.metadata.analysis_id === id
            ? { ...item, response }
            : item,
        ),
      );
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setControllingReview(null);
    }
  }

  const pendingAnalyses = Array.from(
    new Set(
      conversation
        .filter((item) =>
          ["queued", "running"].includes(
            item.response.metadata.analysis_status ?? "",
          ),
        )
        .map((item) => item.response.metadata.analysis_id)
        .filter((id): id is string => Boolean(id)),
    ),
  ).join(",");

  useEffect(() => {
    if (!pendingAnalyses) return;
    let active = true;
    let timeout: ReturnType<typeof setTimeout>;
    async function refresh() {
      try {
        const updates = await Promise.all(
          pendingAnalyses.split(",").map((id) => api.chatAnalysis(id)),
        );
        if (!active) return;
        setConversation((items) =>
          items.map((item) => {
            const response = updates.find(
              (update) =>
                item.response.metadata.answer_mode === "collection_analysis" &&
                update.metadata.analysis_id ===
                  item.response.metadata.analysis_id,
            );
            return response ? { ...item, response } : item;
          }),
        );
      } catch (err) {
        if (active) setError(getErrorMessage(err));
      }
      if (active) timeout = setTimeout(refresh, 2000);
    }
    timeout = setTimeout(refresh, 2000);
    return () => {
      active = false;
      clearTimeout(timeout);
    };
  }, [pendingAnalyses]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!question.trim()) {
      setError("Enter a question before sending.");
      return;
    }

    try {
      setSubmitting(true);
      setError(null);
      const previousReview = [...conversation]
        .reverse()
        .find(
          (item) =>
            item.response.metadata.answer_mode === "collection_analysis" &&
            (item.response.metadata.analysis_collection ?? "") === collection,
        );
      const response = await api.chatQuery({
        review_id: previousReview?.response.metadata.analysis_id,
        question,
        collection: collection || undefined,
        retrieval_mode: retrievalMode,
        top_k: topK,
        rerank,
        analysis_scope: analysisScope,
      });
      setConversation((current) => [{ question, response }, ...current]);
      setQuestion("");
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setSubmitting(false);
    }
  }

  const latest = conversation[0]?.response;

  return (
    <>
      <section className="flex flex-col gap-2">
        <h1 className="text-3xl font-semibold">RAG chat</h1>
        <p className="text-muted-foreground">
          Ask local documents and inspect every cited source chunk, retrieval
          score, and page or line range behind the answer.
        </p>
      </section>

      <div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(320px,390px)]">
        <Card className="min-h-[660px] min-w-0">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <SafeIcon icon={MessageSquareText} />
              Conversation
            </CardTitle>
            <CardDescription>
              Answers cite retrieved chunks as [n]. Empty retrieval and local
              model fallback states are shown explicitly.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex min-h-[540px] flex-col justify-between gap-6">
            <div className="flex flex-col gap-5">
              {conversation.length ? (
                conversation.map((item, index) => (
                  <article
                    key={`${item.question}-${index}`}
                    className="grid gap-3 rounded-md border bg-background p-4"
                  >
                    <div className="flex flex-col gap-2 rounded-md bg-muted/60 p-3">
                      <span className="text-xs font-medium text-muted-foreground">
                        Question
                      </span>
                      <p className="text-sm leading-6">{item.question}</p>
                    </div>
                    <div className="grid gap-3">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge variant="secondary">
                          {answerModeLabel(item.response.metadata.answer_mode)}
                        </Badge>
                        {item.response.metadata.answer_cached ? (
                          <Badge variant="secondary">cached answer</Badge>
                        ) : null}
                        {item.response.metadata.answer_mode ===
                        "collection_analysis" ? (
                          <Badge variant="outline">sources on request</Badge>
                        ) : (
                          <Badge variant="outline">
                            {item.response.citations.length} citations
                          </Badge>
                        )}
                        <Badge variant="outline">
                          {item.response.metadata.answer_mode ===
                          "collection_analysis"
                            ? "all stored text"
                            : item.response.metadata.retrieval_strategy &&
                                item.response.metadata.retrieval_strategy !==
                                  item.response.metadata.retrieval_mode
                              ? `${item.response.metadata.retrieval_mode} → ${item.response.metadata.retrieval_strategy}`
                              : item.response.metadata.retrieval_mode}
                        </Badge>
                        {citationStatusLabel(item.response) ? (
                          <Badge variant="outline">
                            {citationStatusLabel(item.response)}
                          </Badge>
                        ) : null}
                        <Badge variant="outline">
                          {formatLatency(item.response.metadata.latency_ms)}
                        </Badge>
                      </div>
                      {item.response.metadata.answer_mode ===
                      "collection_analysis" ? (
                        <ReviewProgress metadata={item.response.metadata} />
                      ) : (
                        <>
                          <p className="text-xs leading-5 text-muted-foreground">
                            {answerModeDescription(item.response)}
                          </p>
                          <p className="text-xs leading-5 text-muted-foreground">
                            {retrievalCoverageDescription(item.response)}
                          </p>
                        </>
                      )}
                      {item.response.metadata.analysis_routing_error ? (
                        <p
                          role="status"
                          className="text-xs text-muted-foreground"
                        >
                          Automatic scope selection was unavailable; this answer
                          uses retrieved passages only.{" "}
                          {item.response.metadata.analysis_routing_error}
                        </p>
                      ) : null}
                      {item.response.metadata.generation_error ? (
                        <p className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive">
                          {item.response.metadata.answer_mode ===
                          "collection_analysis"
                            ? "Collection review error: "
                            : "Local model fallback: "}
                          {item.response.metadata.generation_error}
                        </p>
                      ) : null}
                      <p className="whitespace-pre-line text-sm leading-7">
                        {item.response.answer}
                      </p>
                      {["queued", "running"].includes(
                        item.response.metadata.analysis_status ?? "",
                      ) ? (
                        <div
                          role="status"
                          className="grid gap-2 text-xs text-muted-foreground"
                        >
                          <Button
                            type="button"
                            variant="outline"
                            disabled={
                              controllingReview ===
                              item.response.metadata.analysis_id
                            }
                            onClick={() =>
                              controlReview(
                                item.response.metadata.analysis_id!,
                                "cancel",
                              )
                            }
                          >
                            Stop review
                          </Button>
                          <span>
                            Stops further batches. An active model call may
                            finish before it releases the model.
                          </span>
                        </div>
                      ) : null}
                      {["cancelled", "failed"].includes(
                        item.response.metadata.analysis_status ?? "",
                      ) ? (
                        <Button
                          type="button"
                          variant="outline"
                          disabled={
                            controllingReview ===
                            item.response.metadata.analysis_id
                          }
                          onClick={() =>
                            controlReview(
                              item.response.metadata.analysis_id!,
                              "resume",
                            )
                          }
                        >
                          Resume review
                        </Button>
                      ) : null}
                      {item.response.inventory?.length ? (
                        <section
                          className="rounded-md border p-3"
                          aria-label="Extracted results"
                        >
                          <div className="flex flex-wrap items-center justify-between gap-3">
                            <p className="text-sm font-medium">
                              Extracted results (
                              {item.response.inventory.length})
                            </p>
                            <Button
                              type="button"
                              variant="outline"
                              onClick={() =>
                                downloadInventory(item.question, item.response)
                              }
                            >
                              {item.response.metadata.analysis_status ===
                              "complete"
                                ? "Download full list (.txt)"
                                : "Download results so far (.txt)"}
                            </Button>
                          </div>
                          <ul className="mt-3 grid max-h-96 gap-2 overflow-auto text-sm">
                            {item.response.inventory
                              .slice(0, INVENTORY_PREVIEW_LIMIT)
                              .map((entry) => (
                                <li key={entry.name}>
                                  <span className="font-medium">
                                    {entry.name}
                                  </span>
                                  {entry.variants &&
                                  entry.variants.length > 1 ? (
                                    <span
                                      className="ml-2 text-xs text-muted-foreground"
                                      title={entry.variants.join(" · ")}
                                    >
                                      +{entry.variants.length - 1} spelling
                                      {entry.variants.length > 2 ? "s" : ""}
                                    </span>
                                  ) : null}
                                  {item.response.metadata.analysis_id ? (
                                    <ResultSources
                                      reviewId={
                                        item.response.metadata.analysis_id
                                      }
                                      value={entry.name}
                                    />
                                  ) : null}
                                </li>
                              ))}
                          </ul>
                          {item.response.inventory.length >
                          INVENTORY_PREVIEW_LIMIT ? (
                            <p className="mt-3 text-xs text-muted-foreground">
                              Showing the first {INVENTORY_PREVIEW_LIMIT} of{" "}
                              {item.response.inventory.length} results. Download
                              the text file for the full extracted list.
                            </p>
                          ) : null}
                        </section>
                      ) : null}
                    </div>
                  </article>
                ))
              ) : (
                <EmptyState
                  icon={FileSearch}
                  title="Ask your indexed documents"
                  description="Ask about a specific document, or request a full list of named people, organizations, projects, or other entities across your documents."
                />
              )}
              {submitting ? <Skeleton className="h-32 w-full" /> : null}
              {error ? (
                <div className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
                  <SafeIcon icon={AlertCircle} />
                  <span className="ml-2">{error}</span>
                </div>
              ) : null}
            </div>

            <form
              className="rounded-md border bg-background p-3"
              onSubmit={handleSubmit}
            >
              <div className="mb-3 grid gap-3 sm:grid-cols-2">
                <label className="grid min-w-0 gap-1.5 text-xs font-medium">
                  Collection
                  <select
                    className="h-10 w-full min-w-0 rounded-md border bg-background px-3 pr-8 text-sm"
                    title={collection || "All collections"}
                    value={collection}
                    onChange={(event) => setCollection(event.target.value)}
                    aria-label="Collection"
                    disabled={loadingCollections}
                  >
                    <option value="">All collections</option>
                    {collections.map((item) => (
                      <option key={item.id} value={item.name}>
                        {item.name}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="grid min-w-0 gap-1.5 text-xs font-medium">
                  Search mode
                  <select
                    className="h-10 rounded-md border bg-background px-3 text-sm"
                    value={retrievalMode}
                    onChange={(event) =>
                      setRetrievalMode(event.target.value as RetrievalMode)
                    }
                    aria-label="Retrieval mode"
                  >
                    <option value="hybrid">hybrid</option>
                    <option value="vector">vector</option>
                    <option value="metadata-filtered">metadata-filtered</option>
                  </select>
                </label>
                <label className="grid gap-1.5 text-xs font-medium">
                  Source chunks (top-k)
                  <Input
                    type="number"
                    min={1}
                    max={20}
                    value={topK}
                    onChange={(event) => setTopK(Number(event.target.value))}
                    aria-label="Top k"
                  />
                </label>
                <label className="flex h-10 self-end items-center gap-2 rounded-md border px-3 text-sm">
                  <input
                    type="checkbox"
                    checked={rerank}
                    onChange={(event) => setRerank(event.target.checked)}
                  />
                  Rerank
                </label>
              </div>
              <label className="mb-3 grid gap-1.5 text-xs font-medium">
                Answer scope
                <select
                  className="h-10 w-full rounded-md border bg-background px-3 text-sm"
                  aria-label="Answer scope"
                  value={analysisScope}
                  onChange={(event) =>
                    setAnalysisScope(event.target.value as typeof analysisScope)
                  }
                >
                  <option value="auto">Auto: lookups + matching sets</option>
                  <option value="retrieved">Passage lookup</option>
                  <option value="collection">
                    Full review (slow, explicit)
                  </option>
                </select>
              </label>
              <details className="mb-4 rounded-md bg-muted/50 p-3 text-xs leading-5 text-muted-foreground">
                <summary className="cursor-pointer font-medium text-foreground">
                  How search works
                </summary>
                <dl className="mt-2 grid gap-2">
                  <div>
                    <dt className="font-medium text-foreground">
                      Answer scope
                    </dt>
                    <dd>
                      Auto uses fast passage search for ordinary questions and
                      can reuse a saved review of the unchanged collection. The
                      local model recognizes requests for matching names, dates,
                      identifiers, amounts, or other values and starts a
                      collection review; “all” or “list” is not required. Choose
                      Passage lookup to always stay with top-k sources. Full
                      review is a slower scan for matching values, with Stop and
                      Resume controls. It ignores search mode, top-k, and
                      rerank. Verified text-segment extractions are cached for
                      reuse. Numeric sums and non-text image interpretation are
                      not supported by full review.
                    </dd>
                  </div>
                  <div>
                    <dt className="font-medium text-foreground">Vector</dt>
                    <dd>
                      Finds passages with similar meaning, even when they use
                      different words. Falls back to keyword search if vector
                      search is unavailable or returns no results.
                    </dd>
                  </div>
                  <div>
                    <dt className="font-medium text-foreground">Hybrid</dt>
                    <dd>
                      Combines meaning-based vector search with BM25 keyword
                      search, then merges their rankings.
                    </dd>
                  </div>
                  <div>
                    <dt className="font-medium text-foreground">
                      Metadata-filtered
                    </dt>
                    <dd>
                      Uses vector search within the selected collection. Chat
                      does not currently expose additional metadata filters;
                      with All collections selected, this behaves like vector
                      mode.
                    </dd>
                  </div>
                  <div>
                    <dt className="font-medium text-foreground">
                      Source chunks (top-k)
                    </dt>
                    <dd>
                      The maximum number of passages returned for a lookup, from
                      1 to 20. Several passages may come from one document. A
                      larger number does not establish a complete collection
                      inventory.
                    </dd>
                  </div>
                  <div>
                    <dt className="font-medium text-foreground">Rerank</dt>
                    <dd>
                      Reorders retrieved candidates using keyword relevance
                      (BM25) for your question before selecting the final
                      passages. It does not scan additional documents.
                    </dd>
                  </div>
                </dl>
              </details>
              <div className="flex gap-3">
                <Input
                  value={question}
                  onChange={(event) => setQuestion(event.target.value)}
                  placeholder="Ask a question about your documents..."
                />
                <Button disabled={submitting}>
                  <SafeIcon icon={Send} />
                  {submitting ? "Sending" : "Send"}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>

        <div className="flex min-w-0 flex-col gap-4">
          <Card className="min-w-0">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <SafeIcon icon={SlidersHorizontal} />
                Retrieval settings
              </CardTitle>
              <CardDescription>
                Latest response metadata returned by the chat endpoint.
              </CardDescription>
            </CardHeader>
            <CardContent className="grid gap-3 text-sm">
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Embedding</span>
                <span className="min-w-0 truncate text-right font-medium">
                  {latest?.metadata.embedding_model ?? "Pending"}
                </span>
              </div>
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Answer model</span>
                <span className="min-w-0 truncate text-right font-medium">
                  {latest?.metadata.llm_model ?? "Pending"}
                </span>
              </div>
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Top-k</span>
                <span className="text-right font-medium">
                  {latest?.metadata.answer_mode === "collection_analysis"
                    ? "Not used for full review"
                    : (latest?.metadata.retrieval_top_k ?? topK)}
                </span>
              </div>
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Rerank</span>
                <span className="text-right font-medium">
                  {latest?.metadata.answer_mode === "collection_analysis"
                    ? "Not used for full review"
                    : String(latest?.metadata.rerank ?? rerank)}
                </span>
              </div>
              <div className="grid grid-cols-[120px_minmax(0,1fr)] items-center gap-3">
                <span className="text-muted-foreground">Retrieval latency</span>
                <span className="text-right font-medium">
                  {latest
                    ? formatLatency(latest.metadata.retrieval_latency_ms)
                    : "Pending"}
                </span>
              </div>
            </CardContent>
          </Card>

          {latest?.citations.length ? (
            latest.citations.map((citation) => (
              <CitationCard
                key={citation.chunk_id}
                sourceNumber={citation.source_number}
                document={citation.document}
                documentId={citation.document_id}
                chunkId={citation.chunk_id}
                retrievalSource={citation.retrieval_source}
                range={lineRange(
                  citation.start_line,
                  citation.end_line,
                  citation.page,
                )}
                score={formatScore(citation.score)}
                text={citation.text_preview}
              />
            ))
          ) : (
            <Card>
              <CardHeader>
                <CardTitle>Retrieved evidence</CardTitle>
                <CardDescription>
                  {latest
                    ? "The latest answer did not include citations."
                    : "Cited source chunks will appear here after a question."}
                </CardDescription>
              </CardHeader>
            </Card>
          )}
        </div>
      </div>
    </>
  );
}
